from pyspark.sql.types import (
    StructType, 
    StructField, 
    TimestampType, 
    StringType,
    BooleanType, 
    LongType, 
    DoubleType, 
    IntegerType,
    MapType
)

upbit_schema = StructType([
    StructField("timestamp", IntegerType(), nullable=False),
    StructField("latency-kafka", IntegerType(), nullable=False),
    StructField("windowStartTime", IntegerType(), nullable=False),
    StructField("windowEndTime", IntegerType(), nullable=False),
    StructField("isotime", TimestampType(), nullable=False),
    StructField("symbol", StringType(), nullable=False),
    StructField("data", StructType([
        StructField("symbol", StringType(), nullable=False),
        StructField("timestamp", TimestampType(), nullable=False),
        StructField("datetime", StringType(), nullable=False),
        StructField("high", DoubleType(), nullable=True),
        StructField("low", DoubleType(), nullable=True),
        StructField("bid", DoubleType(), nullable=True),
        StructField("bidVolume", DoubleType(), nullable=True),
        StructField("ask", DoubleType(), nullable=True),
        StructField("askVolume", DoubleType(), nullable=True),
        StructField("vwap", DoubleType(), nullable=True),
        StructField("open", DoubleType(), nullable=True),
        StructField("close", DoubleType(), nullable=True),
        StructField("last", DoubleType(), nullable=True),
        StructField("previousClose", DoubleType(), nullable=True),
        StructField("change", DoubleType(), nullable=True),
        StructField("percentage", DoubleType(), nullable=True),
        StructField("average", DoubleType(), nullable=True),
        StructField("baseVolume", DoubleType(), nullable=True),
        StructField("quoteVolume", DoubleType(), nullable=True),
        StructField("info", StructType([
            StructField("type", StringType(), nullable=True),
            StructField("code", StringType(), nullable=True),
            StructField("opening_price", DoubleType(), nullable=True),
            StructField("high_price", DoubleType(), nullable=True),
            StructField("low_price", DoubleType(), nullable=True),
            StructField("trade_price", DoubleType(), nullable=True),
            StructField("prev_closing_price", DoubleType(), nullable=True),
            StructField("acc_trade_price", DoubleType(), nullable=True),
            StructField("change", StringType(), nullable=True),
            StructField("change_price", DoubleType(), nullable=True),
            StructField("signed_change_price", DoubleType(), nullable=True),
            StructField("change_rate", DoubleType(), nullable=True),
            StructField("signed_change_rate", DoubleType(), nullable=True),
            StructField("ask_bid", StringType(), nullable=True),
            StructField("trade_volume", DoubleType(), nullable=True),
            StructField("acc_trade_volume", DoubleType(), nullable=True),
            StructField("trade_date", StringType(), nullable=True),
            StructField("trade_time", StringType(), nullable=True),
            StructField("trade_timestamp", TimestampType(), nullable=True),
            StructField("acc_ask_volume", DoubleType(), nullable=True),
            StructField("acc_bid_volume", DoubleType(), nullable=True),
            StructField("highest_52_week_price", DoubleType(), nullable=True),
            StructField("highest_52_week_date", StringType(), nullable=True),
            StructField("lowest_52_week_price", DoubleType(), nullable=True),
            StructField("lowest_52_week_date", StringType(), nullable=True),
            StructField("market_state", StringType(), nullable=True),
            StructField("is_trading_suspended", BooleanType(), nullable=True),
            StructField("delisting_date", StringType(), nullable=True),
            StructField("market_warning", StringType(), nullable=True),
            StructField("timestamp", TimestampType(), nullable=True),
            StructField("acc_trade_price_24h", DoubleType(), nullable=True),
            StructField("acc_trade_volume_24h", DoubleType(), nullable=True),
            StructField("stream_type", StringType(), nullable=True)
        ]))
    ])),
    StructField("exchangeRate", DoubleType(), nullable=False)
])

bybit_schema = StructType([
    StructField("timestamp", IntegerType(), nullable=False),
    StructField("latency-kafka", IntegerType(), nullable=False),
    StructField("windowStartTime", IntegerType(), nullable=False),
    StructField("windowEndTime", IntegerType(), nullable=False),
    StructField("isotime", TimestampType(), nullable=False),
    StructField("symbol", StringType(), nullable=False),
    StructField("data", StructType([
        StructField("symbol", StringType(), nullable=False),
        StructField("timestamp", LongType(), nullable=False),
        StructField("datetime", StringType(), nullable=False),
        StructField("high", DoubleType(), nullable=False),
        StructField("low", DoubleType(), nullable=False),
        StructField("bid", DoubleType(), nullable=False),
        StructField("bidVolume", DoubleType(), nullable=False),
        StructField("ask", DoubleType(), nullable=False),
        StructField("askVolume", DoubleType(), nullable=False),
        StructField("vwap", DoubleType(), nullable=False),
        StructField("open", DoubleType(), nullable=False),
        StructField("close", DoubleType(), nullable=False),
        StructField("last", DoubleType(), nullable=False),
        StructField("previousClose", DoubleType(), nullable=True),
        StructField("change", DoubleType(), nullable=False),
        StructField("percentage", DoubleType(), nullable=False),
        StructField("average", DoubleType(), nullable=False),
        StructField("baseVolume", DoubleType(), nullable=False),
        StructField("quoteVolume", DoubleType(), nullable=False),
        StructField("info", MapType(StringType(), StringType()), nullable=False)
    ]), nullable=False),
    StructField("exchangeRate", DoubleType(), nullable=False)
])